numpy 是一个运行速度非常快的数学库，主要用于数组计算，包含
 - 一个强大的N维数组对象ndarray
 - 广播功能函数
 - 整合C/C++/Fortran 代码的工具
 - 线性代数、傅里叶变换、随机数生成等功能

Numpy 通常与SciPy 和 Matplotlib 一起使用，这种组合广泛用于替代 MatLab,是一个强大的科学计算环境，有助于我们通过Python 学习数据科学或者机器学习

##  NumPy Ndarray 对象

In [2]:
import numpy as np
a = np.array([1,2,3])
print(a)

[1 2 3]


In [6]:
#多于一个维度
import numpy as np
a = np.array([[1,2],[3,4]])
print (a)

[[1 2]
 [3 4]]


In [10]:
#z最小维度
b = np.array([1,2,3,4,5],ndmin=2)
print(b)

[[1 2 3 4 5]]


In [11]:
#dtype 参数
import numpy as np
a = np.array([1,2,3],dtype=complex)
print(a)

[1.+0.j 2.+0.j 3.+0.j]


ndarray 对象由计算机内存的连续一维部分组成，并结合索引模式，将每个元素映射到内存块中的一个位置。内存块以行顺序或列顺序来保存元素

 ## Numpy 数据类型

numpy 支持的数据类型比Python 内置的类型要多很多，基本上可以和C语言的数据类型对应上

数据类型对象(dtype) 用来描述与数组对应的内存区域是如何使用

In [12]:
import numpy as np
#使用标量类型
dt = np.dtype(np.int32)
print(dt)

int32


In [14]:
import numpy as np
#int8,int16,int32,int64 四种数据类型可以使用字符串'i1',i2,i4,i8 代替
dt = np.dtype('i4')
print(dt)

int32


In [16]:
import numpy as np
#字节顺序标注
dt = np.dtype('<i4')
print(dt)

int32


In [ ]:
下面实例展示结构化数据类型的使用， 类型字段和对应的实际类型将被创建

In [20]:
#首先创建结构化数据类型
import numpy as np
dt = np.dtype([('age',np.int8)])
print(dt)
#将数据类型应用于ndarray 对象
a = np.array([(10,),(20,),(30,)],dtype=dt)
print(a)
#类型字段可以用于存取实际的age列
print(a['age'])


[('age', 'i1')]
[(10,) (20,) (30,)]
[10 20 30]


定义一个结构化数据类型student

In [25]:
import numpy as np
student = np.dtype([('name','S20'),('age','i1'),('marks','f4')])
a = np.array([('age',21,50),('x',18,75)],dtype=student)
print(student)
print(a.size)

[('name', 'S20'), ('age', 'i1'), ('marks', '<f4')]
2


In [ ]:
每个内建类型都有一个唯一定义它的字符代码